title: PT-MTI Blog
description: Thoughts, notes, and technical explorations
baseurl: ""
url: "https://india7-lab.github.io"

theme: minima

author:
  name: PT Metro Timur Indonusa
  email: india73927383837383883@gmail.com

# Navigation
header_pages:
  - about.md

# Markdown settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  
sass:
  style: compressed
